[tool.poetry]
name = "pyprudens"
version = "0.1.0"
description = ""
authors = ["marios <msthoma@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
